apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.componentId }}-config
  namespace: ${{ values.namespace }}
data:
  redis.conf: |
    maxmemory ${{ values.maxmemory }}
    maxmemory-policy allkeys-lru
    appendonly yes
    save 900 1
    save 300 10