apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ parameters.componentId }}-pvc
  namespace: {{ parameters.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ parameters.storageSize }}