{% if values.exposeService %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.componentId }}
  namespace: ${{ values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: ${{ values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{ values.componentId }}
            port:
              number: 8080
  {% if values.tlsEnabled %}
  tls:
  - hosts:
    - ${{ values.hostname }}
    secretName: ${{ values.componentId }}-tls
  {% endif %}
{% endif %}