apiVersion: v1
kind: Service
metadata:
  name: ${{ values.componentId }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.componentId }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: ${{ values.port }}
    protocol: TCP
  selector:
    app: ${{ values.componentId }}