apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.componentId }}
  namespace: ${{ parameters.namespace }}
  labels:
    app: ${{ parameters.componentId }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: ${{ parameters.port }}
    protocol: TCP
  selector:
    app: ${{ parameters.componentId }}