apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.componentId }}-service
spec:
  selector:
    app: ${{ parameters.componentId }}
  ports:
    - protocol: TCP
      port: ${{ parameters.port }}
      targetPort: ${{ parameters.port }}
  type: ClusterIP