apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: diploma-templates
  description: Collection of software templates for Diploma project
spec:
  targets:
    # Шаблоны приложений (используй полный GitHub URL)
    - https://github.com/H1KKAR1/backstage_templates/blob/master/software-templates/default-system/template.yaml
    - https://github.com/H1KKAR1/backstage_templates/blob/master/software-templates/python-service/template.yaml
    - https://github.com/H1KKAR1/backstage_templates/blob/master/software-templates/react-frontend/template.yaml
    
    # Инфраструктурные шаблоны
    - https://github.com/H1KKAR1/backstage_templates/blob/master/infrastructure-templates/postgres/template.yaml
    - https://github.com/H1KKAR1/backstage_templates/blob/master/infrastructure-templates/redis/template.yaml
    - https://github.com/H1KKAR1/backstage_templates/blob/master/infrastructure-templates/rabbitmq/template.yaml
    - https://github.com/H1KKAR1/backstage_templates/blob/master/infrastructure-templates/monitoring/template.yaml
