apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.componentId }}-secret
  namespace: ${{ values.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: ${{ values.defaultUser }}
  RABBITMQ_DEFAULT_PASS: ${{ values.rabbitmqPassword }}
  RABBITMQ_ERLANG_COOKIE: ${{ values.erlangCookie }}