apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.componentId }}-secret
  namespace: ${{ values.namespace }}
  annotations:
    fluxcd.io/ignore: "false"
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${{ values.databasePassword | default( 'postgres123' ) }}
  POSTGRES_USER: ${{ values.databaseUser }}
  POSTGRES_DB: ${{ values.databaseName }}