apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ parameters.componentId }}-deployment
  labels:
    app: ${{ parameters.componentId }}
    backstage.io/name: ${{ parameters.componentId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ parameters.componentId }}
  template:
    metadata:
      labels:
        app: ${{ parameters.componentId }}
    spec:
      containers:
        - name: main
          
          image: ${{ parameters.dockerImage }}  
          ports:
            - containerPort: ${{ parameters.port }}
          env:
            - name: SERVICE_TYPE
              value: ${{ parameters.serviceType }}
          resources:
            limits:
              cpu: ${{ parameters.cpuLimit }}
              memory: ${{ parameters.memoryLimit }}