apiVersion: v1
kind: Secret
metadata:
  name: ${{ parameters.componentId }}-secret
  namespace: ${{ parameters.namespace }}
  annotations:
    fluxcd.io/ignore: "false"
type: Opaque
stringData:
  POSTGRES_PASSWORD: ${{ parameters.databasePassword | default( 'postgres123' ) }}
  POSTGRES_USER: ${{ parameters.databaseUser }}
  POSTGRES_DB: ${{ parameters.databaseName }}