apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.componentId }}
  namespace: ${{ parameters.namespace }}
  labels:
    app: ${{ parameters.componentId }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: ${{ parameters.componentId }}