apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ${{ values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:${{ values.grafanaVersion }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "${{ values.grafanaPassword }}"
        resources:
          limits:
            memory: ${{ values.grafanaMemoryLimit }}
            cpu: ${{ values.grafanaCpuLimit }}
          requests:
            memory: ${{ values.grafanaMemoryRequest }}
            cpu: ${{ values.grafanaCpuRequest }}
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ${{ values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana