apiVersion: v1
kind: Secret
metadata:
  name: ${{ parameters.componentId }}-secret
  namespace: ${{ parameters.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: ${{ parameters.defaultUser }}
  RABBITMQ_DEFAULT_PASS: ${{ parameters.rabbitmqPassword | default( 'rabbitmq123' ) }}
  RABBITMQ_ERLANG_COOKIE: ${{ parameters.erlangCookie | default( 'cookie123' ) }}