apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-monitoring
  title: Monitoring Stack
  description: Lightweight Prometheus + Grafana
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Monitoring Configuration
      required:
        - componentId
        - namespace
      properties:
        componentId:
          title: Service Name
          type: string
          default: "monitoring"
        namespace:
          title: Namespace
          type: string
          default: "monitoring"
        grafanaPassword:
          title: Grafana Admin Password
          type: string
          default: "admin"
        storageSize:
          title: Prometheus Storage Size
          type: string
          default: "10Gi"
        gitopsRepoUrl:
          title: GitOps Repository URL
          type: string
          default: "github.com?owner=H1KKAR1&repo=Diplom"

  steps:
    - id: generate-manifests
      name: Generate Monitoring Manifests
      action: fetch:template
      input:
        url: https://github.com/H1KKAR1/backstage_templates/tree/master/infrastructure-templates/monitoring/skeleton-flux
        targetPath: ./generated/infrastructure/monitoring
        values:
          componentId: ${{ parameters.componentId }}
          namespace: ${{ parameters.namespace }}
          grafanaPassword: ${{ parameters.grafanaPassword }}
          storageSize: ${{ parameters.storageSize }}

    - id: push-to-gitops
      name: Push to GitOps Repository
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.gitopsRepoUrl }}
        title: "Add monitoring stack"
        description: "This PR adds Prometheus and Grafana monitoring stack"
        branchName: backstage/add-monitoring
        sourcePath: ./generated
        targetPath: .
        update: true

  output:
    links:
      - title: Monitoring Manifests
        url: ${{ parameters.gitopsRepoUrl }}/tree/main/infrastructure/monitoring